"""Shared constants for Phase 1-2 of CGM-Rec."""

DATASET_ML_100K = "ml_100k"

SUPPORTED_DATASETS = (DATASET_ML_100K,)

TRAIN_FILENAME = "train_ml100k.json"
TEST_FILENAME = "test_ml100k.json"
INFO_FILENAME = "info_ML100k.json"

SESSION_PREFIX = "Current session interactions:"
CANDIDATE_MARKER = "\nCandidate Set:"
ITEM_PATTERN = r'\d+\."([^"]+)"'

DEFAULT_CANDIDATE_COUNT = 20
DEFAULT_WARMUP_MODE = "ratio"
DEFAULT_WARMUP_RATIO = 0.2
DEFAULT_WARMUP_COUNT = 50
DEFAULT_RANDOM_SEED = 42
DEFAULT_KEYWORD_TOP_K = 5
DEFAULT_CO_OCCUR_WINDOW = 5
DEFAULT_INCLUDE_DESCRIPTION = True
DEFAULT_PHASE3_EPOCHS = 3
DEFAULT_PHASE3_LEARNING_RATE = 0.05
DEFAULT_PHASE4_EPISODIC_MAX_RECORDS = 500
DEFAULT_PHASE4_MAX_TENTATIVE_EDGES = 250

WARMUP_MODE_RATIO = "ratio"
WARMUP_MODE_COUNT = "count"
SUPPORTED_WARMUP_MODES = (WARMUP_MODE_RATIO, WARMUP_MODE_COUNT)

INDEX_BASE_ZERO = "zero_based"
INDEX_BASE_ONE = "one_based"
INDEX_BASE_UNKNOWN = "unknown"

NODE_TYPE_ITEM = "item"
NODE_TYPE_CATEGORY = "category"
NODE_TYPE_KEYWORD = "keyword"
NODE_TYPE_DESCRIPTION = "description"

EDGE_REL_BELONGS_TO = "belongs_to"
EDGE_REL_HAS_KEYWORD = "has_keyword"
EDGE_REL_HAS_DESCRIPTION = "has_description"
EDGE_REL_CO_OCCURS = "co_occurs_with"

EDGE_SOURCE_METADATA = "metadata"
EDGE_SOURCE_WARMUP = "warmup_behavior"
EDGE_SOURCE_ONLINE = "online_update"
EDGE_SOURCE_TENTATIVE = "online_tentative"

FEATURE_SHARED_CATEGORIES = "shared_categories"
FEATURE_SHARED_KEYWORDS = "shared_keywords"
FEATURE_CO_OCCUR_SCORE = "co_occur_score"
FEATURE_CANDIDATE_CATEGORY_COUNT = "candidate_category_count"
FEATURE_CANDIDATE_KEYWORD_COUNT = "candidate_keyword_count"
FEATURE_HAS_DESCRIPTION = "has_description"
FEATURE_CANDIDATE_IN_DEGREE = "candidate_in_degree"

PHASE3_FEATURE_NAMES = (
    FEATURE_SHARED_CATEGORIES,
    FEATURE_SHARED_KEYWORDS,
    FEATURE_CO_OCCUR_SCORE,
    FEATURE_CANDIDATE_CATEGORY_COUNT,
    FEATURE_CANDIDATE_KEYWORD_COUNT,
    FEATURE_HAS_DESCRIPTION,
    FEATURE_CANDIDATE_IN_DEGREE,
)
